version: '3.0'
services:
  stats-server:
    build: ewm-stats-service/stats-server
    image: stats_image
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - EWM_STATS_SERVER_URL=http://stats-server:9090


  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=stats

  ewm-service:
    build: ewm-main-service
    image: main_image
    container_name: main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - EWM_STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewv-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm
